# Generated by Django 5.0.2 on 2024-02-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requestFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(max_length=120)),
                ('tissue', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SingleCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=120)),
                ('p_value', models.FloatField()),
                ('adj_p_value', models.FloatField()),
                ('organ_tissue', models.CharField(max_length=120)),
                ('organ', models.CharField(max_length=120)),
            ],
        ),
    ]
