# Generated by Django 5.0.2 on 2024-02-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='requestFilters',
            new_name='MMVAEParams',
        ),
    ]
