# Generated by Django 5.0.2 on 2024-02-24 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_requestfilters_mmvaeparams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MMVAEParams',
            new_name='MMVAEParameter',
        ),
    ]
