# Generated by Django 5.0.2 on 2024-03-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_mmvaeparams_mmvaeparameter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MMVAEParameter',
        ),
        migrations.DeleteModel(
            name='SingleCell',
        ),
    ]
