# Generated by Django 4.2.11 on 2024-03-19 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_delete_mmvaeparameter_delete_singlecell'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv', models.FileField(upload_to='')),
                ('npz', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RequestFilters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('organType', models.CharField(max_length=100)),
                ('tissue', models.CharField(max_length=100)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
